version: 0.2
env:
    variables:
        BUILDSPEC_PATH: "pipeline/buildspec"
        DEPLOY_PATH: "stage_1_prebuild"
        ENV_PATH: "pipeline/buildspec"
        ENV_SH: "env.sh"
phases:
    install:
        commands:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_1_install.sh
        finally:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_1_install_finally.sh
    pre_build:
        commands:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_2_prebuild.sh
        finally:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_2_prebuild_finally.sh
    build:
        commands:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_3_build.sh
        finally:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_3_build_finally.sh
    post_build:
        commands:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_4_postbuild.sh
        finally:
            - $CODEBUILD_SRC_DIR/$BUILDSPEC_PATH/$DEPLOY_PATH/phase_4_postbuild_finally.sh
